// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
// ignore: prefer-match-file-name
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZTQouDAVjy5HpOC5I97-JXXN6Na0FmVA',
    authDomain: 'agelospanagiotakis.firebaseapp.com',
    projectId: 'agelospanagiotakis',
    storageBucket: 'agelospanagiotakis.appspot.com',
    messagingSenderId: '382749452780',
    appId: '1:382749452780:web:ddae0d78e8e9bf77b7b8c9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZTQouDAVjy5HpOC5I97-JXXN6Na0FmVA',
    authDomain: 'agelospanagiotakis.firebaseapp.com',
    projectId: 'agelospanagiotakis',
    storageBucket: 'agelospanagiotakis.appspot.com',
    messagingSenderId: '382749452780',
    appId: '1:382749452780:web:ddae0d78e8e9bf77b7b8c9',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZTQouDAVjy5HpOC5I97-JXXN6Na0FmVA',
    authDomain: 'agelospanagiotakis.firebaseapp.com',
    projectId: 'agelospanagiotakis',
    storageBucket: 'agelospanagiotakis.appspot.com',
    messagingSenderId: '382749452780',
    appId: '1:382749452780:web:ddae0d78e8e9bf77b7b8c9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZTQouDAVjy5HpOC5I97-JXXN6Na0FmVA',
    authDomain: 'agelospanagiotakis.firebaseapp.com',
    projectId: 'agelospanagiotakis',
    storageBucket: 'agelospanagiotakis.appspot.com',
    messagingSenderId: '382749452780',
    appId: '1:382749452780:web:ddae0d78e8e9bf77b7b8c9',
    iosBundleId: '',
  );
}
